### ISSUE TITLE
treatment upload to BLR: progress

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#109]
@gsautter 
What have you decided now with the upload ot treatments? I though you suggestion was perfect to upload some and check and then slowly move up the speed?
Cheers
Donat

**Comment by gsautter** [comment]
Yes it was ... no need to update north of 300K treatment depositions if any of us sports something that requires changing.
We have some 300 treatments uploaded now (see http://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+doc.doi+doc.zenodoDepId+doc.name+doc.articleUuid+doc.articleDoi+doc.articleZenodoDepId+doc.uploadDate&FP-doc.zenodoDepId=1-&FA-doc.zenodoDepId=count-distinct&FA-doc.articleZenodoDepId=count-distinct&format=HTML), so this is a good basis for checking. Please go all and look around, and let me know if something odd jumps your eye.

**Comment by gsautter** [comment]
Once we're satisfied with those 300 initial treatments, we can either move up to, say, 3,000 and do another round of eyeballing, or go full broadside right away.

Considering the non-negligible amount of time the upload will take (some 5 seconds per treatment, amounting to ~15K treatments per day, and thus some 3 weeks total for the whole collection), we should most likely start collecting examples we want uploaded before Biodiversite Next and start with those, and then fire the full broadside only after the Leiden meeting.
So, everybody, check your plans for presentations in Leiden and let me know which treatments you need on BLR for that purpose. I'd greatly appreciate if you give me either the exact treatment UUID (for individual treatments) or the taxon names (for groups of treatments) because that will make my life a lot easier regarding the console based triggering of the uploads. Wish-list away, guys !!!

**Comment by myrmoteras** [comment]
@mguidoti @tcatapano @teodorgeorgiev @lyubomirpenev @millerjeremya @punkish  please have a look at the treatments on BLR and comment, both that you agree, and what need be changed, could be changed.

https://zenodo.org/communities/biosyslit/search?page=1&size=20&subtype=taxonomictreatment

create an issue on this issue tracker and add the lable "treatment@zenodo"
